### ISSUE TITLE
Ads now appear under posts

### ISSUE THREAD

**Issue by ZTerlizzese** [haoict/reddit-no-ads#3]
Ads now appear under posts between the upvote/downvote arrows and comments. Would you consider updating your tweak to include these ads as well?

Edit: I changed my comment to be more constructive after reviewing your code.

**Comment by Rezrazi** [comment]
![image](https://user-images.githubusercontent.com/2086576/99785891-15d18d00-2b1e-11eb-8872-a59de8b8f5ad.png)

**Comment by haoict** [comment]
This should fix the problem: 
https://github.com/haoict/reddit-no-ads/releases/tag/v1.2.0
