### ISSUE TITLE
Collapsing first comment causes all to disappear

### ISSUE THREAD

**Issue by robertybob** [haoict/reddit-no-ads#4]
As per title. When I have this tweak installed and I try to collapse the first comment in a thread, all of the comments in a page will disappear

**Comment by haoict** [comment]
Yeah I also saw that, I made a quick fix [here](https://github.com/haoict/reddit-no-ads/releases/tag/v1.1.1), it's still showing empty space for the placeholder but at least the situation is better though.

**Comment by robertybob** [comment]
Thank you for pushing a fix so quickly :)
