### ISSUE TITLE
Blank spot where ad would be under post

### ISSUE THREAD

**Issue by adamgeo1** [haoict/reddit-no-ads#5]
![B3F386CD-6375-49BC-BF53-01C65F461838](https://user-images.githubusercontent.com/69363323/112744988-e1118e80-8f72-11eb-9216-56e3dfe6f5b6.png)
This happens on all posts that would have an ad there.

**Comment by haoict** [comment]
This should fix the problem: 
https://github.com/haoict/reddit-no-ads/releases/tag/v1.2.0
