### ISSUE TITLE
Promoted ads are back on latest Reddit version (5/9/21)

### ISSUE THREAD

**Issue by Redan24** [haoict/reddit-no-ads#6]
Ads are back in some areas, haven’t tested the entire app but so far ads/Promoted are appearing under directly under the post and above the comment section 

![A352AD5F-0E05-4D78-AA98-F40FA88A891C](https://user-images.githubusercontent.com/83919871/117581257-c160a080-b0b0-11eb-9160-ef11e382fce4.png)

**Comment by haoict** [comment]
This should fix the problem: 
https://github.com/haoict/reddit-no-ads/releases/tag/v1.2.0
