### ISSUE TITLE
Doesn’t work on iPad 

### ISSUE THREAD

**Issue by rasch3n** [haoict/reddit-no-ads#7]
Promotions are still there

**Comment by haoict** [comment]
This should fix the problem: 
https://github.com/haoict/reddit-no-ads/releases/tag/v1.2.0

**Comment by rasch3n** [comment]
It is still not working on my iPad!

**Comment by haoict** [comment]
- Do you have jailbreak detection bypass tweaks (FlyJB, HideJB, kernbypass, ...)?
- If yes, are you sure that it does not block this tweak?
- Also, can you provide a screenshot please

**Comment by rasch3n** [comment]
My fault! I had set choisy to block stuff on reddit!
Sorry for that!
And thanks for your support
