### ISSUE TITLE
Promoted ads showing again

### ISSUE THREAD

**Issue by Hukuma1** [haoict/reddit-no-ads#8]
Heya! Thanks for this tweak. I just updated Reddit and it seems some promoted posts are making it through again. Just started with today's update version `2021.33.0`. Screens attached.

![promoted](https://user-images.githubusercontent.com/54511555/130901378-1f0b4c0f-affc-4647-a5bc-d2caf2ba21d0.jpg)

![version](https://user-images.githubusercontent.com/54511555/130901430-166f1cbf-a18a-49ed-8e27-5d9a4c4dbd57.PNG)

![version2](https://user-images.githubusercontent.com/54511555/130901460-c1583964-de74-4bcd-8237-fcbd26571f27.PNG)

**Comment by Nigel1992** [comment]
Same issue here

**Comment by haoict** [comment]
I updated the tweak, please check

**Comment by Hukuma1** [comment]
Looks like a cat and mouse game has begun. Ads showing again in version `2021.35.0` Unless your tweak has hardcoded versions it applies to?

**Comment by haoict** [comment]
@Hukuma1 yes, reddit updated their core classes (migrated to Swift) in 2021.35.0
I updated the tweak as well

**Comment by Hukuma1** [comment]
Works great, thanks again! :)

**Comment by Hukuma1** [comment]
Version 2021.47.0 seems to be showing some promoted ads within posts themselves. Right underneath.


![newads2](https://user-images.githubusercontent.com/54511555/147280852-599f6430-925e-4069-83a4-e2b59a1a3cdc.jpg)

**Comment by Hukuma1** [comment]
Looks like ads are back again in latest version. Not sure if Reddit made more Swift migrations or from some other reason. Keep up the good work, I almost forgot how bad it was before your tweak.

**Comment by GoddeerisEdouard** [comment]
> Looks like ads are back again in latest version. Not sure if Reddit made more Swift migrations or from some other reason. Keep up the good work, I almost forgot how bad it was before your tweak.

I can confirm this as well
Since v 2022.20.0, promoted ads are showing again.
I downgraded to 2022.18.1 & the promoted ads are removed again 👍
